# Generated by Django 4.2.30 on 2026-08-18 12:41

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cotacoes", "0005_alter_cotacao_status"),
        (
            "seguradoras",
            "0006_seguradora_api_ambiente_seguradora_api_client_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissaoSeguradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integracao",
                    models.CharField(
                        help_text="Cópia de Seguradora.integracao no momento em que a emissão começou.",
                        max_length=30,
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("cotada", "Cotada"),
                            ("minuta", "Minuta gerada"),
                            ("aguardando", "Aguardando seguradora"),
                            ("emitida", "Emitida"),
                            ("recusada", "Recusada"),
                        ],
                        default="cotada",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Id da cotação na seguradora.",
                        max_length=50,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "premio_liquido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "premio_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "taxa",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "comissao_percentual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "comissao_valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "numero_parcelas",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "numero_max_parcelas",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "opcoes_parcelamento",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("tem_pendencias", models.BooleanField(default=False)),
                (
                    "pendencias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("anexos_enviados", models.PositiveSmallIntegerField(default=0)),
                (
                    "ambiente",
                    models.CharField(
                        help_text="Congela Seguradora.api_ambiente no passo 1: um id de sandbox não existe em produção.",
                        max_length=10,
                    ),
                ),
                (
                    "dados_cotados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Snapshot do que foi enviado. Os passos seguintes comparam com a cotação atual.",
                    ),
                ),
                (
                    "codigo_retorno",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("mensagem", models.TextField(blank=True, default="")),
                (
                    "url_cotacao",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("url_minuta", models.URLField(blank=True, default="", max_length=500)),
                (
                    "ultimo_request",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "ultima_resposta",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cotacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissao",
                        to="cotacoes.cotacao",
                    ),
                ),
                (
                    "seguradora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emissoes",
                        to="seguradoras.seguradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emissão na seguradora",
                "verbose_name_plural": "Emissões na seguradora",
                "db_table": "emissoes_seguradora",
                "ordering": ["-id"],
            },
        ),
    ]
