# Generated by Django 4.2.30 on 2026-08-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cotacoes", "0005_alter_cotacao_status"),
        ("emissoes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissaoseguradora",
            name="cotacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emissoes",
                to="cotacoes.cotacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="emissaoseguradora",
            constraint=models.UniqueConstraint(
                fields=("cotacao", "seguradora"),
                name="emissao_unica_por_cotacao_seguradora",
            ),
        ),
    ]
