# Generated by Django 4.2.30 on 2026-07-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seguradoras", "0004_seguradora_api_ou_name_seguradora_api_senha_and_more"),
        ("modalidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModalidadeSeguradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_seguradora",
                    models.CharField(
                        help_text="Código da modalidade no catálogo da seguradora.",
                        max_length=50,
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcado suspende o mapeamento sem perder o código.",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguradoras",
                        to="modalidades.modalidade",
                    ),
                ),
                (
                    "seguradora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modalidades",
                        to="seguradoras.seguradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modalidade da Seguradora",
                "verbose_name_plural": "Modalidades da Seguradora",
                "db_table": "modalidade_seguradoras",
                "ordering": ["seguradora__nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="modalidadeseguradora",
            constraint=models.UniqueConstraint(
                fields=("modalidade", "seguradora"), name="uniq_modalidade_seguradora"
            ),
        ),
    ]
