# Generated by Django 4.2.30 on 2026-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Aprovado', 'Aprovado')], default='Iniciado', max_length=20),
        ),
    ]
