# Generated by Django 4.2.30 on 2026-07-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cotacoes", "0002_cotacao_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Iniciado", "Iniciado"),
                    ("Aprovado", "Aprovado"),
                    ("Emitido", "Emitido"),
                ],
                default="Iniciado",
                max_length=20,
            ),
        ),
    ]
