# Generated by Django 4.2.30 on 2026-07-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0004_cotacao_premio_cotacao_seguradora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Aprovado', 'Aprovado'), ('Emitido', 'Emitido')], default='Aprovado', max_length=20),
        ),
    ]
