# Generated by Django 4.2.30 on 2026-08-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seguradoras", "0005_rename_vencimento_dias"),
    ]

    operations = [
        migrations.AddField(
            model_name="seguradora",
            name="api_ambiente",
            field=models.CharField(
                choices=[("sandbox", "Sandbox"), ("producao", "Produção")],
                default="sandbox",
                help_text="Um id gerado no sandbox não existe em produção; trocar isto invalida emissões em andamento.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="seguradora",
            name="api_client_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="seguradora",
            name="api_client_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Segredo da API. Nunca sai em resposta de GET.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="seguradora",
            name="integracao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sem integração (emissão manual)"),
                    ("junto", "Junto Seguros — API v2"),
                ],
                default="",
                help_text="Vazio = emissão manual. Preenchido = qual conector responde por esta seguradora.",
                max_length=30,
            ),
        ),
    ]
