# Generated by Django 5.2.16 on 2026-07-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apolices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apolice",
            name="vencimento_boleto",
            field=models.DateField(blank=True, null=True),
        ),
    ]
