# Generated by Django 4.2.30 on 2026-08-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apolices', '0002_apolice_vencimento_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='apolice',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Cancelada', 'Cancelada')], default='Ativa', max_length=20),
        ),
    ]
