# Generated by Django 4.2.30 on 2026-06-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomador',
            name='ativarCotacao',
        ),
        migrations.AddField(
            model_name='tomador',
            name='ativar_cotacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tomador',
            name='habilitar_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tomador',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
