# Generated by Django 4.2.30 on 2026-06-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomador', '0002_remove_tomador_ativarcotacao_tomador_ativar_cotacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomador',
            name='cnpj',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
