# Generated by Django 4.2.30 on 2026-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='recebimento',
            field=models.CharField(blank=True, choices=[('lucro', 'Lucro'), ('comissao', 'Comissão'), ('premio', 'Prêmio')], default='', max_length=20),
        ),
    ]
