# Generated by Django 4.2.30 on 2026-08-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0002_alter_corretor_recebimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretor',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='percentual',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='recebimento',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='url_saida',
        ),
    ]
