# Generated by Django 4.2.30 on 2026-06-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_cnpj_customuser_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('financeiro', 'Financeiro'), ('usuario', 'Usuário'), ('corretor', 'Corretor'), ('produtor', 'Produtor'), ('auto', 'Auto'), ('tomador', 'Tomador')], default='usuario', max_length=20),
        ),
    ]
