# Generated by Django 4.2.30 on 2026-06-26 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(blank=True, default='', max_length=255)),
                ('usuario_username', models.CharField(blank=True, default='', max_length=150)),
                ('acao', models.CharField(choices=[('LOGIN', 'Login'), ('CRIAÇÃO', 'Criação'), ('ATUALIZAÇÃO', 'Atualização'), ('EXCLUSÃO', 'Exclusão')], max_length=20)),
                ('entidade', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividades',
                'ordering': ['-criado_em'],
            },
        ),
    ]
