# Generated by Django 4.2.30 on 2026-08-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='object_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
