# Generated by Django 4.2.30 on 2026-08-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_atividade_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='usuario_username',
        ),
    ]
