# Generated by Django 4.2.30 on 2026-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atividades", "0003_remove_usuario_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="acao",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("CRIAÇÃO", "Criação"),
                    ("ATUALIZAÇÃO", "Atualização"),
                    ("EXCLUSÃO", "Exclusão"),
                    ("ENVIO", "Envio"),
                ],
                max_length=20,
            ),
        ),
    ]
