# Generated by Django 4.2.30 on 2026-06-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tomador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=255)),
                ('produtor', models.CharField(default='CAJUINA SEGUROS', max_length=100)),
                ('corretora', models.CharField(default='CAJUINA', max_length=100)),
                ('contato', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('habilitar_email', models.BooleanField(default=False)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('celular', models.CharField(blank=True, default='', max_length=20)),
                ('cep', models.CharField(blank=True, default='', max_length=10)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('ativar_cotacao', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tomador',
                'verbose_name_plural': 'Tomadores',
                'db_table': 'tomadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('qualificacao', models.CharField(blank=True, choices=[('Sócio Administrador', 'Sócio Administrador'), ('Diretor', 'Diretor'), ('Sócio', 'Sócio'), ('Administrador', 'Administrador'), ('Procurador', 'Procurador')], default='', max_length=50)),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='tomadores.tomador')),
            ],
            options={
                'verbose_name': 'Sócio',
                'verbose_name_plural': 'Sócios',
                'db_table': 'tomadores_socios',
            },
        ),
        migrations.CreateModel(
            name='ContatoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_adicionais', to='tomadores.tomador')),
            ],
            options={
                'verbose_name': 'Contato Adicional',
                'verbose_name_plural': 'Contatos Adicionais',
                'db_table': 'tomadores_contatos',
            },
        ),
    ]
