# Generated by Django 4.2.30 on 2026-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tomadores", "0006_tomador_criado_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tomador",
            name="nome",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
