# Generated by Django 4.2.30 on 2026-08-05 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tomadores", "0007_alter_tomador_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tomador",
            name="corretora",
        ),
    ]
