# Generated by Django 4.2.30 on 2026-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tomadores", "0008_remove_tomador_corretora"),
    ]

    operations = [
        migrations.AddField(
            model_name="tomador",
            name="corretora",
            field=models.CharField(blank=True, default="CAJUINA", max_length=100),
        ),
    ]
