# Generated by Django 4.2.30 on 2026-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomadores', '0009_tomador_corretora'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomadorseguradora',
            name='junto_data_ultima_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tomadorseguradora',
            name='junto_validade_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
