# Generated by Django 4.2.30 on 2026-08-19 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomadores', '0010_tomadorseguradora_junto_data_ultima_verificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomadorseguradora',
            name='taxa_data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tomadorseguradora',
            name='taxa_junto_modalidade_descricao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tomadorseguradora',
            name='taxa_junto_modalidade_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tomadorseguradora',
            name='taxa_origem',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tomadorseguradora',
            name='taxa',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Zero deixa a seguradora fora das cotações deste tomador.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
